# Generated by Django 4.1.2 on 2022-12-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_contributor_issues_remove_house_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_name", models.CharField(max_length=50)),
                ("user", models.CharField(max_length=50)),
                ("language_detail", models.CharField(max_length=1000)),
                ("language", models.CharField(max_length=10)),
                ("stars", models.IntegerField()),
                ("forks", models.IntegerField()),
                ("issues", models.IntegerField()),
                ("topic", models.CharField(max_length=1000)),
            ],
        ),
    ]
