# Generated by Django 4.1.2 on 2022-12-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_basic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("repo_name", models.CharField(max_length=50)),
                ("user", models.CharField(max_length=50)),
                (
                    "week",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("days", models.CharField(max_length=50)),
                ("total", models.IntegerField()),
            ],
        ),
    ]
