# Generated by Django 4.1.2 on 2022-12-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pull",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_name", models.CharField(max_length=50)),
                ("user", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="basic",
            name="description",
            field=models.CharField(default=None, max_length=500),
        ),
    ]
