# Generated by Django 4.1.2 on 2022-12-12 11:48

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_pull_basic_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("login", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50, null=True)),
                ("organizations_url", models.CharField(max_length=100, null=True)),
                ("type", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="pull",
            name="closed_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="pull",
            name="created_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="pull", name="locked", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pull",
            name="merged_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="pull",
            name="number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pull",
            name="state",
            field=models.CharField(default=io.open, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pull",
            name="title",
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pull",
            name="updated_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="basic",
            name="id",
            field=models.CharField(
                default="65600975", max_length=20, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="pull",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(model_name="pull", name="user",),
        migrations.AddField(
            model_name="pull",
            name="user",
            field=models.ManyToManyField(to="apps.user"),
        ),
    ]
