# Generated by Django 4.1.2 on 2022-12-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_user_pull_closed_at_pull_created_at_pull_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basic", name="commits", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="basic", name="pulls", field=models.IntegerField(null=True),
        ),
    ]
