# Generated by Django 4.1.2 on 2022-12-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_basic_commits_basic_pulls"),
    ]

    operations = [
        migrations.AddField(
            model_name="basic",
            name="contributor",
            field=models.IntegerField(null=True),
        ),
    ]
