# Generated by Django 4.1.2 on 2022-12-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0008_basic_contributor"),
    ]

    operations = [
        migrations.RemoveField(model_name="basic", name="contributor",),
    ]
