# Generated by Django 4.1.2 on 2022-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0009_remove_basic_contributor"),
    ]

    operations = [
        migrations.RemoveField(model_name="basic", name="pulls",),
        migrations.AddField(
            model_name="basic",
            name="close_pulls",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="basic",
            name="contributor",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="basic", name="open_pulls", field=models.IntegerField(null=True),
        ),
    ]
