# Generated by Django 4.1.2 on 2022-12-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0011_alter_basic_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="organizations_url",),
    ]
