# Generated by Django 4.1.2 on 2022-12-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0013_alter_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
                ("reply_at", models.DateTimeField()),
                ("message", models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(model_name="pull", name="user",),
        migrations.AddField(
            model_name="user",
            name="commit",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="issues",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="pulls",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="reviews",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
