# Generated by Django 4.1.2 on 2022-12-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0014_commit_remove_pull_user_user_commit_user_issues_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="commit", name="id",),
        migrations.AlterField(
            model_name="commit",
            name="sha",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
