# Generated by Django 4.1.2 on 2022-12-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0015_remove_commit_id_alter_commit_sha"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="type",),
    ]
