# Generated by Django 4.1.2 on 2022-12-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0017_pull_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="Pull", new_name="Pulls",),
    ]
