# Generated by Django 4.1.2 on 2022-12-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0018_rename_pull_pulls"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="Person",),
    ]
