# Generated by Django 4.1.2 on 2022-12-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0019_rename_user_person"),
    ]

    operations = [
        migrations.RenameModel(old_name="Person", new_name="User",),
    ]
