# Generated by Django 4.1.2 on 2022-12-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0020_rename_person_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="commit",
            name="repo_name",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commit",
            name="user",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
