# Generated by Django 4.1.2 on 2022-12-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0021_commit_repo_name_commit_user"),
    ]

    operations = [
        migrations.RenameField(model_name="commit", old_name="sha", new_name="id",),
    ]
