# Generated by Django 4.1.2 on 2022-12-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0027_alter_user_commit_alter_user_id_alter_user_issues_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="user", old_name="user_id", new_name="user",),
    ]
