# Generated by Django 4.1.2 on 2022-12-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0028_rename_user_id_user_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="user",),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
