# Generated by Django 4.1.2 on 2022-12-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0029_remove_user_user_user_user_id_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stars",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starred_at", models.DateTimeField()),
                ("repo_name", models.CharField(max_length=50)),
                ("user", models.CharField(max_length=50)),
                ("login", models.CharField(max_length=50)),
            ],
            options={"unique_together": {("user", "repo_name", "login")},},
        ),
    ]
