# Generated by Django 4.1.2 on 2022-12-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0030_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="basic",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
