# Generated by Django 4.1.2 on 2022-12-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0031_basic_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issues", old_name="create_time", new_name="created_at",
        ),
    ]
