# Generated by Django 4.1.2 on 2022-12-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0032_rename_create_time_issues_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_name", models.CharField(max_length=50)),
                ("user", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50)),
                ("counts", models.IntegerField()),
            ],
        ),
    ]
