# Generated by Django 4.1.2 on 2022-12-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0033_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="type",
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
