# Generated by Django 4.0 on 2021-12-31 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mirror_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, null=True)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=100, null=True)),
                ('Date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Date_of_lastpush', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Language', models.CharField(max_length=50, null=True)),
                ('Number_of_forks', models.IntegerField(null=True)),
                ('Number_of_stars', models.IntegerField(null=True)),
                ('Home_page', models.CharField(max_length=50, null=True)),
                ('Html_url', models.URLField(null=True)),
                ('users_participated', models.ManyToManyField(related_name='usersParticipated', to='mirror_user.UserProfile')),
            ],
            options={
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('author_name', models.CharField(max_length=100, null=True)),
                ('author_email', models.EmailField(max_length=254, null=True)),
                ('author_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('commiter_name', models.CharField(max_length=100, null=True)),
                ('commiter_email', models.EmailField(max_length=254, null=True)),
                ('commiter_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('sha', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100, null=True)),
                ('comment_count', models.IntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.project')),
            ],
        ),
    ]
