# Generated by Django 4.0 on 2021-12-31 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users_participated',
            field=models.ManyToManyField(related_name='usersParticipated', to=settings.AUTH_USER_MODEL),
        ),
    ]
