# Generated by Django 4.0 on 2022-01-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_project_users_participated'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
