# Generated by Django 4.1.2 on 2022-11-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_project_project_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "contributor_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("login", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
