# Generated by Django 4.1.2 on 2022-11-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_contributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="project",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
