# Generated by Django 4.0 on 2021-12-31 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('0', '女'), ('1', '男')], default='1', max_length=5, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机')),
                ('org', models.CharField(blank=True, max_length=200, null=True, verbose_name='组织')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user', verbose_name='用户')),
            ],
        ),
    ]
