# Generated by Django 4.0 on 2022-01-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mirror_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(blank=True, null=True, verbose_name='主题')),
                ('info', models.TextField(blank=True, null=True, verbose_name='信息')),
                ('realname', models.CharField(blank=True, max_length=15, null=True, verbose_name='真实姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='auth.user', verbose_name='用户')),
            ],
        ),
    ]
