# Generated by Django 4.0 on 2022-01-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror_user', '0002_usercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='验证码'),
        ),
    ]
