# Generated by Django 4.0 on 2022-01-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror_user', '0003_userprofile_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verification',
            field=models.CharField(blank=True, default='0', max_length=5, null=True, verbose_name='验证码'),
        ),
    ]
